# image will be published to ghcr.io/<user>/<name>
name: my-ublue
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-nvidia
image-version: 39 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - usr: /usr
          # copy static configurations
          #
          # copies config/files/usr into your image's /usr
          #
          # configuration you wish to end up in /etc/ on the booted system
          # should be added into /usr/etc/ as that is the proper "distro"
          # config directory on ostree. Read more in the files module's README

  - type: rpm-ostree
    repos: 
      - https://copr.fedorainfracloud.org/coprs/ublue-os/akmods/repo/fedora-39/ublue-os-akmods-fedora-39.repo
    install:
      - fish
      - mock
      - systemd-boot-unsigned
      - tuned
      - vdpauinfo
      - kmod-openrgb
      - kmod-winesync
      - kmod-openrazer
      - kmod-wl
    remove:
      - xorg-x11-drv-nvidia-power # Breaks Wayland
      - power-profiles-daemon # Effectively unmantained
      - gnome-software # 10GB of RAM when closed? no thanks
      - gnome-software-rpm-ostree 
      # - firefox # default firefox removed in favor of flatpak
      # - firefox-langpacks # langpacks needs to also be removed to prevent dependency problems

  - type: bling # configure what to pull in from ublue-os/bling
    install:
      - justfiles
        # add "!include /usr/share/ublue-os/just/bling.just"
        # in your custom.just (added by default) or local justfile
      - nix-installer # shell shortcuts for determinate system's nix installers
      - ublue-os-wallpapers
      # - ublue-update # https://github.com/ublue-os/ublue-update
      # - dconf-update-service # a service unit that updates the dconf db on boot
      # - devpod # https://devpod.sh/ as an rpm
      
  - type: fonts
    fonts:
      nerd-fonts:
        - FiraCode # don't add "Nerd Font" suffix.
        - Hack
        - SourceCodePro
        - Terminus
        - JetBrainsMono
        - NerdFontsSymbolsOnly
      google-fonts:
        - Roboto
        - Open Sans
        
  - type: script
    scripts:
      # this sets up the proper policy & signing files for signed images to work
      - build-kmods.sh

  - type: script
    scripts:
      # this sets up the proper policy & signing files for signed images to work
      - signing.sh
