# image will be published to ghcr.io/<user>/<name>
name: my-ublue
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 40 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - usr: /usr
          # copy static configurations
          #
          # copies config/files/usr into your image's /usr
          #
          # configuration you wish to end up in /etc/ on the booted system
          # should be added into /usr/etc/ as that is the proper "distro"
          # config directory on ostree. Read more in the files module's README
  - type: containerfile
    snippets: 
      - COPY --from=docker.io/mikefarah/yq /usr/bin/yq /usr/bin/yq
      - COPY --from=ghcr.io/ublue-os/bluefin-cli /usr/bin/atuin /usr/bin/atuin
      - COPY --from=ghcr.io/ublue-os/bluefin-cli /usr/share/bash-prexec /usr/share/bash-prexec
      - COPY --from=cgr.dev/chainguard/dive:latest /usr/bin/dive /usr/bin/dive
      - COPY --from=cgr.dev/chainguard/flux:latest /usr/bin/flux /usr/bin/flux
      - COPY --from=cgr.dev/chainguard/helm:latest /usr/bin/helm /usr/bin/helm
      - COPY --from=cgr.dev/chainguard/ko:latest /usr/bin/ko /usr/bin/ko
      - COPY --from=cgr.dev/chainguard/minio-client:latest /usr/bin/mc /usr/bin/mc
      - COPY --from=cgr.dev/chainguard/kubectl:latest /usr/bin/kubectl /usr/bin/kubectl
  - type: akmods
    install: 
      - openrazer
      - openrgb
      - v4l2loopback
      - winesync
      - wl
      - ryzen-smu
      - xone
      - nvidia
  - type: rpm-ostree
    repos: 
      #- https://copr.fedorainfracloud.org/coprs/ublue-os/akmods/repo/fedora-39/ublue-os-akmods-fedora-39.repo
      - https://copr.fedorainfracloud.org/coprs/hyperreal/better_fonts/repo/fedora-%OS_VERSION%/hyperreal-better_fonts-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/fynnfreyer/nautilus-copypath/repo/fedora-%OS_VERSION%/fynnfreyer-nautilus-copypath-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/getpagespeed/wrk/repo/fedora-%OS_VERSION%/getpagespeed-wrk-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/rhcontainerbot/podman-next/repo/fedora-%OS_VERSION%/rhcontainerbot-podman-next-fedora-%OS_VERSION%.repo
    install:
      - fish
      - zsh
      - systemd-boot-unsigned # systemd-boot efi binaries
      - tuned # replace power-profiles-daemon
      - tuned-ppd
      - tuned-utils
      - tuned-utils-systemtap
      - tuned-profiles-atomic
      - vdpauinfo
      - ttmkfdir
      - fontconfig-font-replacements
      - fontconfig-enhanced-defaults
      - moby-engine
      - flatpak-builder
      - telnet
      - netcat
      - virt-manager
      - nautilus-copypath
      - gnome-shell-extension-appindicator
      - gnome-disk-utility
      - lm_sensors
      - lynis
      - mediainfo
      - chkrootkit
      - httpie
      - liquidctl
      - solaar
      - gnome-shell-extension-appindicator
      - gnome-shell-extension-blur-my-shell
      - adw-gtk3-theme
      - wrk
      - android-tools
      - podman
    remove:
      #- xorg-x11-drv-nvidia-power # breaks Wayland
      - power-profiles-daemon # effectively unmantained
      - gnome-software # 10GB of RAM when closed? no thanks
      - gnome-software-rpm-ostree 
      # - firefox # default firefox removed in favor of flatpak
      # - firefox-langpacks # langpacks needs to also be removed to prevent dependency problems
      - gnome-tour # annoying

  - type: bling # configure what to pull in from ublue-os/bling
    install:
      #- justfiles
        # add "!include /usr/share/ublue-os/just/bling.just"
        # in your custom.just (added by default) or local justfile
      #- nix-installer # shell shortcuts for determinate system's nix installers
      - ublue-os-wallpapers
      #- container-tools
      # - ublue-update # https://github.com/ublue-os/ublue-update
      # - dconf-update-service # a service unit that updates the dconf db on boot
      # - devpod # https://devpod.sh/ as an rpm
      
  - type: fonts
    fonts:
      nerd-fonts:
        - FiraCode # don't add "Nerd Font" suffix.
        - Hack
        - SourceCodePro
        - Terminus
        - JetBrainsMono
        - NerdFontsSymbolsOnly
      google-fonts:
        - Roboto
        - Open Sans
        
  - type: script
    scripts:
      - ms-fonts.sh
      #- java.sh
      - gnome-patched.sh
      - prompt.sh
      - other.sh
      
  - type: systemd
    system:
      enabled:
        - tuned.service
      disabled:
        - ModemManager.service
        - pcscd.service
        - pcscd.socket
        - gssproxy.service
        - sssd-kcm.service
        - sssd-kcm.socket

  - type: containerfile
    containerfiles:
      #- nvidia

  - type: default-flatpaks
    notify: false   # Send notification after install/uninstall is finished (true/false)
    system:
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      repo-title: "Flathub (system-wide)" # Optional; this sets the remote's user-facing name in graphical frontends like GNOME Software

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
